// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api.proto

package serverlessapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MethodAttestation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The type of attestation method being used.
	MethodType string `protobuf:"bytes,1,opt,name=method_type,json=methodType,proto3" json:"method_type,omitempty"`
	// Required. The version of the attestation method being used.
	MethodVersion string `protobuf:"bytes,2,opt,name=method_version,json=methodVersion,proto3" json:"method_version,omitempty"`
	// Required. The attestation data to be used for the specified method type.
	Evidence      []byte `protobuf:"bytes,3,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodAttestation) Reset() {
	*x = MethodAttestation{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodAttestation) ProtoMessage() {}

func (x *MethodAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodAttestation.ProtoReflect.Descriptor instead.
func (*MethodAttestation) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *MethodAttestation) GetMethodType() string {
	if x != nil {
		return x.MethodType
	}
	return ""
}

func (x *MethodAttestation) GetMethodVersion() string {
	if x != nil {
		return x.MethodVersion
	}
	return ""
}

func (x *MethodAttestation) GetEvidence() []byte {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type FetchX509SVIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The attestation data of the workload.
	Attestations []*MethodAttestation `protobuf:"bytes,1,rep,name=attestations,proto3" json:"attestations,omitempty"`
	// Optional. The ID of the serverless cluster whose policy set should
	// authorize this request (RFD-194). Empty selects the trust-domain-scoped
	// policy set (backward-compatible).
	ClusterId     string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchX509SVIDRequest) Reset() {
	*x = FetchX509SVIDRequest{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchX509SVIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchX509SVIDRequest) ProtoMessage() {}

func (x *FetchX509SVIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchX509SVIDRequest.ProtoReflect.Descriptor instead.
func (*FetchX509SVIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *FetchX509SVIDRequest) GetAttestations() []*MethodAttestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *FetchX509SVIDRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type FetchX509SVIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Only set if all required attestations were satisfied.
	X509Svids     *X509SVIDResult `protobuf:"bytes,1,opt,name=x509_svids,json=x509Svids,proto3" json:"x509_svids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchX509SVIDResponse) Reset() {
	*x = FetchX509SVIDResponse{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchX509SVIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchX509SVIDResponse) ProtoMessage() {}

func (x *FetchX509SVIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchX509SVIDResponse.ProtoReflect.Descriptor instead.
func (*FetchX509SVIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *FetchX509SVIDResponse) GetX509Svids() *X509SVIDResult {
	if x != nil {
		return x.X509Svids
	}
	return nil
}

type X509SVIDResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. A list of X509SVID messages, each of which includes a single
	// X.509-SVID, its private key, and the bundle for the trust domain.
	Svids []*X509SVID `protobuf:"bytes,1,rep,name=svids,proto3" json:"svids,omitempty"`
	// Optional. CA certificate bundles belonging to foreign trust domains that
	// the workload should trust, keyed by the SPIFFE ID of the foreign trust
	// domain. Bundles are ASN.1 DER encoded.
	FederatedBundles map[string][]byte `protobuf:"bytes,2,rep,name=federated_bundles,json=federatedBundles,proto3" json:"federated_bundles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *X509SVIDResult) Reset() {
	*x = X509SVIDResult{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *X509SVIDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509SVIDResult) ProtoMessage() {}

func (x *X509SVIDResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509SVIDResult.ProtoReflect.Descriptor instead.
func (*X509SVIDResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *X509SVIDResult) GetSvids() []*X509SVID {
	if x != nil {
		return x.Svids
	}
	return nil
}

func (x *X509SVIDResult) GetFederatedBundles() map[string][]byte {
	if x != nil {
		return x.FederatedBundles
	}
	return nil
}

type X509SVID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpiffeId      string                 `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	X509Svid      []byte                 `protobuf:"bytes,2,opt,name=x509_svid,json=x509Svid,proto3" json:"x509_svid,omitempty"`
	X509SvidKey   []byte                 `protobuf:"bytes,3,opt,name=x509_svid_key,json=x509SvidKey,proto3" json:"x509_svid_key,omitempty"`
	Bundle        []byte                 `protobuf:"bytes,4,opt,name=bundle,proto3" json:"bundle,omitempty"`
	Hint          string                 `protobuf:"bytes,5,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *X509SVID) Reset() {
	*x = X509SVID{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *X509SVID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509SVID) ProtoMessage() {}

func (x *X509SVID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509SVID.ProtoReflect.Descriptor instead.
func (*X509SVID) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *X509SVID) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *X509SVID) GetX509Svid() []byte {
	if x != nil {
		return x.X509Svid
	}
	return nil
}

func (x *X509SVID) GetX509SvidKey() []byte {
	if x != nil {
		return x.X509SvidKey
	}
	return nil
}

func (x *X509SVID) GetBundle() []byte {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *X509SVID) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type FetchX509BundlesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The attestation data of the workload.
	Attestations []*MethodAttestation `protobuf:"bytes,1,rep,name=attestations,proto3" json:"attestations,omitempty"`
	// Optional. The ID of the serverless cluster whose policy set should
	// authorize this request (RFD-194). Empty selects the trust-domain-scoped
	// policy set (backward-compatible).
	ClusterId     string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchX509BundlesRequest) Reset() {
	*x = FetchX509BundlesRequest{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchX509BundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchX509BundlesRequest) ProtoMessage() {}

func (x *FetchX509BundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchX509BundlesRequest.ProtoReflect.Descriptor instead.
func (*FetchX509BundlesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *FetchX509BundlesRequest) GetAttestations() []*MethodAttestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *FetchX509BundlesRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type FetchX509BundlesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Only set if all required attestations were satisfied.
	Bundles       *X509BundlesResult `protobuf:"bytes,1,opt,name=bundles,proto3" json:"bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchX509BundlesResponse) Reset() {
	*x = FetchX509BundlesResponse{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchX509BundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchX509BundlesResponse) ProtoMessage() {}

func (x *FetchX509BundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchX509BundlesResponse.ProtoReflect.Descriptor instead.
func (*FetchX509BundlesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *FetchX509BundlesResponse) GetBundles() *X509BundlesResult {
	if x != nil {
		return x.Bundles
	}
	return nil
}

type X509BundlesResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. CA certificate bundles belonging to trust domains that the
	// workload should trust, keyed by the SPIFFE ID of the trust domain.
	// Bundles are ASN.1 DER encoded.
	Bundles       map[string][]byte `protobuf:"bytes,1,rep,name=bundles,proto3" json:"bundles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *X509BundlesResult) Reset() {
	*x = X509BundlesResult{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *X509BundlesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509BundlesResult) ProtoMessage() {}

func (x *X509BundlesResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509BundlesResult.ProtoReflect.Descriptor instead.
func (*X509BundlesResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *X509BundlesResult) GetBundles() map[string][]byte {
	if x != nil {
		return x.Bundles
	}
	return nil
}

type FetchJWTSVIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The attestation data of the workload.
	Attestations []*MethodAttestation `protobuf:"bytes,1,rep,name=attestations,proto3" json:"attestations,omitempty"`
	// Required. The audience for the JWT-SVID.
	Audience []string `protobuf:"bytes,2,rep,name=audience,proto3" json:"audience,omitempty"`
	// Optional. The SPIFFE ID of the workload.
	SpiffeId string `protobuf:"bytes,3,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	// Optional. The ID of the serverless cluster whose policy set should
	// authorize this request (RFD-194). Empty selects the trust-domain-scoped
	// policy set (backward-compatible).
	ClusterId     string `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchJWTSVIDRequest) Reset() {
	*x = FetchJWTSVIDRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchJWTSVIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchJWTSVIDRequest) ProtoMessage() {}

func (x *FetchJWTSVIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchJWTSVIDRequest.ProtoReflect.Descriptor instead.
func (*FetchJWTSVIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *FetchJWTSVIDRequest) GetAttestations() []*MethodAttestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *FetchJWTSVIDRequest) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *FetchJWTSVIDRequest) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *FetchJWTSVIDRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type FetchJWTSVIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Only set if all required attestations were satisfied.
	JwtSvids      *JWTSVIDResult `protobuf:"bytes,1,opt,name=jwt_svids,json=jwtSvids,proto3" json:"jwt_svids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchJWTSVIDResponse) Reset() {
	*x = FetchJWTSVIDResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchJWTSVIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchJWTSVIDResponse) ProtoMessage() {}

func (x *FetchJWTSVIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchJWTSVIDResponse.ProtoReflect.Descriptor instead.
func (*FetchJWTSVIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *FetchJWTSVIDResponse) GetJwtSvids() *JWTSVIDResult {
	if x != nil {
		return x.JwtSvids
	}
	return nil
}

type JWTSVIDResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The list of returned JWT-SVIDs.
	Svids         []*JWTSVID `protobuf:"bytes,1,rep,name=svids,proto3" json:"svids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTSVIDResult) Reset() {
	*x = JWTSVIDResult{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTSVIDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTSVIDResult) ProtoMessage() {}

func (x *JWTSVIDResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTSVIDResult.ProtoReflect.Descriptor instead.
func (*JWTSVIDResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *JWTSVIDResult) GetSvids() []*JWTSVID {
	if x != nil {
		return x.Svids
	}
	return nil
}

type JWTSVID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The SPIFFE ID of the JWT-SVID.
	SpiffeId string `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	// Required. Encoded JWT using JWS Compact Serialization.
	Svid string `protobuf:"bytes,2,opt,name=svid,proto3" json:"svid,omitempty"`
	// Optional. An operator-specified string used to provide guidance on how this
	// identity should be used by a workload when more than one SVID is returned.
	// For example, `internal` and `external` to indicate an SVID for internal or
	// external use, respectively.
	Hint          string `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTSVID) Reset() {
	*x = JWTSVID{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTSVID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTSVID) ProtoMessage() {}

func (x *JWTSVID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTSVID.ProtoReflect.Descriptor instead.
func (*JWTSVID) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *JWTSVID) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *JWTSVID) GetSvid() string {
	if x != nil {
		return x.Svid
	}
	return ""
}

func (x *JWTSVID) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type FetchJWTBundlesRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Attestations []*MethodAttestation   `protobuf:"bytes,1,rep,name=attestations,proto3" json:"attestations,omitempty"`
	// Optional. The ID of the serverless cluster whose policy set should
	// authorize this request (RFD-194). Empty selects the trust-domain-scoped
	// policy set (backward-compatible).
	ClusterId     string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchJWTBundlesRequest) Reset() {
	*x = FetchJWTBundlesRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchJWTBundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchJWTBundlesRequest) ProtoMessage() {}

func (x *FetchJWTBundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchJWTBundlesRequest.ProtoReflect.Descriptor instead.
func (*FetchJWTBundlesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *FetchJWTBundlesRequest) GetAttestations() []*MethodAttestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *FetchJWTBundlesRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type FetchJWTBundlesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Only set if all required attestations were satisfied.
	Bundles       *JWTBundlesResult `protobuf:"bytes,1,opt,name=bundles,proto3" json:"bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchJWTBundlesResponse) Reset() {
	*x = FetchJWTBundlesResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchJWTBundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchJWTBundlesResponse) ProtoMessage() {}

func (x *FetchJWTBundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchJWTBundlesResponse.ProtoReflect.Descriptor instead.
func (*FetchJWTBundlesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *FetchJWTBundlesResponse) GetBundles() *JWTBundlesResult {
	if x != nil {
		return x.Bundles
	}
	return nil
}

type JWTBundlesResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. JWK encoded JWT bundles, keyed by the SPIFFE ID of the trust
	// domain.
	Bundles       map[string][]byte `protobuf:"bytes,1,rep,name=bundles,proto3" json:"bundles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTBundlesResult) Reset() {
	*x = JWTBundlesResult{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTBundlesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTBundlesResult) ProtoMessage() {}

func (x *JWTBundlesResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTBundlesResult.ProtoReflect.Descriptor instead.
func (*JWTBundlesResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *JWTBundlesResult) GetBundles() map[string][]byte {
	if x != nil {
		return x.Bundles
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x1acom.spirl.serverless.alpha\"w\n" +
	"\x11MethodAttestation\x12\x1f\n" +
	"\vmethod_type\x18\x01 \x01(\tR\n" +
	"methodType\x12%\n" +
	"\x0emethod_version\x18\x02 \x01(\tR\rmethodVersion\x12\x1a\n" +
	"\bevidence\x18\x03 \x01(\fR\bevidence\"\x88\x01\n" +
	"\x14FetchX509SVIDRequest\x12Q\n" +
	"\fattestations\x18\x01 \x03(\v2-.com.spirl.serverless.alpha.MethodAttestationR\fattestations\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\"b\n" +
	"\x15FetchX509SVIDResponse\x12I\n" +
	"\n" +
	"x509_svids\x18\x01 \x01(\v2*.com.spirl.serverless.alpha.X509SVIDResultR\tx509Svids\"\x80\x02\n" +
	"\x0eX509SVIDResult\x12:\n" +
	"\x05svids\x18\x01 \x03(\v2$.com.spirl.serverless.alpha.X509SVIDR\x05svids\x12m\n" +
	"\x11federated_bundles\x18\x02 \x03(\v2@.com.spirl.serverless.alpha.X509SVIDResult.FederatedBundlesEntryR\x10federatedBundles\x1aC\n" +
	"\x15FederatedBundlesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x94\x01\n" +
	"\bX509SVID\x12\x1b\n" +
	"\tspiffe_id\x18\x01 \x01(\tR\bspiffeId\x12\x1b\n" +
	"\tx509_svid\x18\x02 \x01(\fR\bx509Svid\x12\"\n" +
	"\rx509_svid_key\x18\x03 \x01(\fR\vx509SvidKey\x12\x16\n" +
	"\x06bundle\x18\x04 \x01(\fR\x06bundle\x12\x12\n" +
	"\x04hint\x18\x05 \x01(\tR\x04hint\"\x8b\x01\n" +
	"\x17FetchX509BundlesRequest\x12Q\n" +
	"\fattestations\x18\x01 \x03(\v2-.com.spirl.serverless.alpha.MethodAttestationR\fattestations\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\"c\n" +
	"\x18FetchX509BundlesResponse\x12G\n" +
	"\abundles\x18\x01 \x01(\v2-.com.spirl.serverless.alpha.X509BundlesResultR\abundles\"\xa5\x01\n" +
	"\x11X509BundlesResult\x12T\n" +
	"\abundles\x18\x01 \x03(\v2:.com.spirl.serverless.alpha.X509BundlesResult.BundlesEntryR\abundles\x1a:\n" +
	"\fBundlesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xc0\x01\n" +
	"\x13FetchJWTSVIDRequest\x12Q\n" +
	"\fattestations\x18\x01 \x03(\v2-.com.spirl.serverless.alpha.MethodAttestationR\fattestations\x12\x1a\n" +
	"\baudience\x18\x02 \x03(\tR\baudience\x12\x1b\n" +
	"\tspiffe_id\x18\x03 \x01(\tR\bspiffeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\"^\n" +
	"\x14FetchJWTSVIDResponse\x12F\n" +
	"\tjwt_svids\x18\x01 \x01(\v2).com.spirl.serverless.alpha.JWTSVIDResultR\bjwtSvids\"J\n" +
	"\rJWTSVIDResult\x129\n" +
	"\x05svids\x18\x01 \x03(\v2#.com.spirl.serverless.alpha.JWTSVIDR\x05svids\"N\n" +
	"\aJWTSVID\x12\x1b\n" +
	"\tspiffe_id\x18\x01 \x01(\tR\bspiffeId\x12\x12\n" +
	"\x04svid\x18\x02 \x01(\tR\x04svid\x12\x12\n" +
	"\x04hint\x18\x03 \x01(\tR\x04hint\"\x8a\x01\n" +
	"\x16FetchJWTBundlesRequest\x12Q\n" +
	"\fattestations\x18\x01 \x03(\v2-.com.spirl.serverless.alpha.MethodAttestationR\fattestations\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\"a\n" +
	"\x17FetchJWTBundlesResponse\x12F\n" +
	"\abundles\x18\x01 \x01(\v2,.com.spirl.serverless.alpha.JWTBundlesResultR\abundles\"\xa3\x01\n" +
	"\x10JWTBundlesResult\x12S\n" +
	"\abundles\x18\x01 \x03(\v29.com.spirl.serverless.alpha.JWTBundlesResult.BundlesEntryR\abundles\x1a:\n" +
	"\fBundlesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x012\xf7\x03\n" +
	"\x11SpiffeWorkloadAPI\x12t\n" +
	"\rFetchX509SVID\x120.com.spirl.serverless.alpha.FetchX509SVIDRequest\x1a1.com.spirl.serverless.alpha.FetchX509SVIDResponse\x12}\n" +
	"\x10FetchX509Bundles\x123.com.spirl.serverless.alpha.FetchX509BundlesRequest\x1a4.com.spirl.serverless.alpha.FetchX509BundlesResponse\x12q\n" +
	"\fFetchJWTSVID\x12/.com.spirl.serverless.alpha.FetchJWTSVIDRequest\x1a0.com.spirl.serverless.alpha.FetchJWTSVIDResponse\x12z\n" +
	"\x0fFetchJWTBundles\x122.com.spirl.serverless.alpha.FetchJWTBundlesRequest\x1a3.com.spirl.serverless.alpha.FetchJWTBundlesResponseB[ZYgithub.com/defakto-security/spiffe-defakto-go/attestingworkloadapi/internal/serverlessapib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_goTypes = []any{
	(*MethodAttestation)(nil),        // 0: com.spirl.serverless.alpha.MethodAttestation
	(*FetchX509SVIDRequest)(nil),     // 1: com.spirl.serverless.alpha.FetchX509SVIDRequest
	(*FetchX509SVIDResponse)(nil),    // 2: com.spirl.serverless.alpha.FetchX509SVIDResponse
	(*X509SVIDResult)(nil),           // 3: com.spirl.serverless.alpha.X509SVIDResult
	(*X509SVID)(nil),                 // 4: com.spirl.serverless.alpha.X509SVID
	(*FetchX509BundlesRequest)(nil),  // 5: com.spirl.serverless.alpha.FetchX509BundlesRequest
	(*FetchX509BundlesResponse)(nil), // 6: com.spirl.serverless.alpha.FetchX509BundlesResponse
	(*X509BundlesResult)(nil),        // 7: com.spirl.serverless.alpha.X509BundlesResult
	(*FetchJWTSVIDRequest)(nil),      // 8: com.spirl.serverless.alpha.FetchJWTSVIDRequest
	(*FetchJWTSVIDResponse)(nil),     // 9: com.spirl.serverless.alpha.FetchJWTSVIDResponse
	(*JWTSVIDResult)(nil),            // 10: com.spirl.serverless.alpha.JWTSVIDResult
	(*JWTSVID)(nil),                  // 11: com.spirl.serverless.alpha.JWTSVID
	(*FetchJWTBundlesRequest)(nil),   // 12: com.spirl.serverless.alpha.FetchJWTBundlesRequest
	(*FetchJWTBundlesResponse)(nil),  // 13: com.spirl.serverless.alpha.FetchJWTBundlesResponse
	(*JWTBundlesResult)(nil),         // 14: com.spirl.serverless.alpha.JWTBundlesResult
	nil,                              // 15: com.spirl.serverless.alpha.X509SVIDResult.FederatedBundlesEntry
	nil,                              // 16: com.spirl.serverless.alpha.X509BundlesResult.BundlesEntry
	nil,                              // 17: com.spirl.serverless.alpha.JWTBundlesResult.BundlesEntry
}
var file_api_proto_depIdxs = []int32{
	0,  // 0: com.spirl.serverless.alpha.FetchX509SVIDRequest.attestations:type_name -> com.spirl.serverless.alpha.MethodAttestation
	3,  // 1: com.spirl.serverless.alpha.FetchX509SVIDResponse.x509_svids:type_name -> com.spirl.serverless.alpha.X509SVIDResult
	4,  // 2: com.spirl.serverless.alpha.X509SVIDResult.svids:type_name -> com.spirl.serverless.alpha.X509SVID
	15, // 3: com.spirl.serverless.alpha.X509SVIDResult.federated_bundles:type_name -> com.spirl.serverless.alpha.X509SVIDResult.FederatedBundlesEntry
	0,  // 4: com.spirl.serverless.alpha.FetchX509BundlesRequest.attestations:type_name -> com.spirl.serverless.alpha.MethodAttestation
	7,  // 5: com.spirl.serverless.alpha.FetchX509BundlesResponse.bundles:type_name -> com.spirl.serverless.alpha.X509BundlesResult
	16, // 6: com.spirl.serverless.alpha.X509BundlesResult.bundles:type_name -> com.spirl.serverless.alpha.X509BundlesResult.BundlesEntry
	0,  // 7: com.spirl.serverless.alpha.FetchJWTSVIDRequest.attestations:type_name -> com.spirl.serverless.alpha.MethodAttestation
	10, // 8: com.spirl.serverless.alpha.FetchJWTSVIDResponse.jwt_svids:type_name -> com.spirl.serverless.alpha.JWTSVIDResult
	11, // 9: com.spirl.serverless.alpha.JWTSVIDResult.svids:type_name -> com.spirl.serverless.alpha.JWTSVID
	0,  // 10: com.spirl.serverless.alpha.FetchJWTBundlesRequest.attestations:type_name -> com.spirl.serverless.alpha.MethodAttestation
	14, // 11: com.spirl.serverless.alpha.FetchJWTBundlesResponse.bundles:type_name -> com.spirl.serverless.alpha.JWTBundlesResult
	17, // 12: com.spirl.serverless.alpha.JWTBundlesResult.bundles:type_name -> com.spirl.serverless.alpha.JWTBundlesResult.BundlesEntry
	1,  // 13: com.spirl.serverless.alpha.SpiffeWorkloadAPI.FetchX509SVID:input_type -> com.spirl.serverless.alpha.FetchX509SVIDRequest
	5,  // 14: com.spirl.serverless.alpha.SpiffeWorkloadAPI.FetchX509Bundles:input_type -> com.spirl.serverless.alpha.FetchX509BundlesRequest
	8,  // 15: com.spirl.serverless.alpha.SpiffeWorkloadAPI.FetchJWTSVID:input_type -> com.spirl.serverless.alpha.FetchJWTSVIDRequest
	12, // 16: com.spirl.serverless.alpha.SpiffeWorkloadAPI.FetchJWTBundles:input_type -> com.spirl.serverless.alpha.FetchJWTBundlesRequest
	2,  // 17: com.spirl.serverless.alpha.SpiffeWorkloadAPI.FetchX509SVID:output_type -> com.spirl.serverless.alpha.FetchX509SVIDResponse
	6,  // 18: com.spirl.serverless.alpha.SpiffeWorkloadAPI.FetchX509Bundles:output_type -> com.spirl.serverless.alpha.FetchX509BundlesResponse
	9,  // 19: com.spirl.serverless.alpha.SpiffeWorkloadAPI.FetchJWTSVID:output_type -> com.spirl.serverless.alpha.FetchJWTSVIDResponse
	13, // 20: com.spirl.serverless.alpha.SpiffeWorkloadAPI.FetchJWTBundles:output_type -> com.spirl.serverless.alpha.FetchJWTBundlesResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
