// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api.proto

package serverlessapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpiffeWorkloadAPI_FetchX509SVID_FullMethodName    = "/com.spirl.serverless.alpha.SpiffeWorkloadAPI/FetchX509SVID"
	SpiffeWorkloadAPI_FetchX509Bundles_FullMethodName = "/com.spirl.serverless.alpha.SpiffeWorkloadAPI/FetchX509Bundles"
	SpiffeWorkloadAPI_FetchJWTSVID_FullMethodName     = "/com.spirl.serverless.alpha.SpiffeWorkloadAPI/FetchJWTSVID"
	SpiffeWorkloadAPI_FetchJWTBundles_FullMethodName  = "/com.spirl.serverless.alpha.SpiffeWorkloadAPI/FetchJWTBundles"
)

// SpiffeWorkloadAPIClient is the client API for SpiffeWorkloadAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpiffeWorkloadAPIClient interface {
	FetchX509SVID(ctx context.Context, in *FetchX509SVIDRequest, opts ...grpc.CallOption) (*FetchX509SVIDResponse, error)
	FetchX509Bundles(ctx context.Context, in *FetchX509BundlesRequest, opts ...grpc.CallOption) (*FetchX509BundlesResponse, error)
	FetchJWTSVID(ctx context.Context, in *FetchJWTSVIDRequest, opts ...grpc.CallOption) (*FetchJWTSVIDResponse, error)
	FetchJWTBundles(ctx context.Context, in *FetchJWTBundlesRequest, opts ...grpc.CallOption) (*FetchJWTBundlesResponse, error)
}

type spiffeWorkloadAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiffeWorkloadAPIClient(cc grpc.ClientConnInterface) SpiffeWorkloadAPIClient {
	return &spiffeWorkloadAPIClient{cc}
}

func (c *spiffeWorkloadAPIClient) FetchX509SVID(ctx context.Context, in *FetchX509SVIDRequest, opts ...grpc.CallOption) (*FetchX509SVIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchX509SVIDResponse)
	err := c.cc.Invoke(ctx, SpiffeWorkloadAPI_FetchX509SVID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiffeWorkloadAPIClient) FetchX509Bundles(ctx context.Context, in *FetchX509BundlesRequest, opts ...grpc.CallOption) (*FetchX509BundlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchX509BundlesResponse)
	err := c.cc.Invoke(ctx, SpiffeWorkloadAPI_FetchX509Bundles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiffeWorkloadAPIClient) FetchJWTSVID(ctx context.Context, in *FetchJWTSVIDRequest, opts ...grpc.CallOption) (*FetchJWTSVIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchJWTSVIDResponse)
	err := c.cc.Invoke(ctx, SpiffeWorkloadAPI_FetchJWTSVID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiffeWorkloadAPIClient) FetchJWTBundles(ctx context.Context, in *FetchJWTBundlesRequest, opts ...grpc.CallOption) (*FetchJWTBundlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchJWTBundlesResponse)
	err := c.cc.Invoke(ctx, SpiffeWorkloadAPI_FetchJWTBundles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpiffeWorkloadAPIServer is the server API for SpiffeWorkloadAPI service.
// All implementations must embed UnimplementedSpiffeWorkloadAPIServer
// for forward compatibility.
type SpiffeWorkloadAPIServer interface {
	FetchX509SVID(context.Context, *FetchX509SVIDRequest) (*FetchX509SVIDResponse, error)
	FetchX509Bundles(context.Context, *FetchX509BundlesRequest) (*FetchX509BundlesResponse, error)
	FetchJWTSVID(context.Context, *FetchJWTSVIDRequest) (*FetchJWTSVIDResponse, error)
	FetchJWTBundles(context.Context, *FetchJWTBundlesRequest) (*FetchJWTBundlesResponse, error)
	mustEmbedUnimplementedSpiffeWorkloadAPIServer()
}

// UnimplementedSpiffeWorkloadAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpiffeWorkloadAPIServer struct{}

func (UnimplementedSpiffeWorkloadAPIServer) FetchX509SVID(context.Context, *FetchX509SVIDRequest) (*FetchX509SVIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchX509SVID not implemented")
}
func (UnimplementedSpiffeWorkloadAPIServer) FetchX509Bundles(context.Context, *FetchX509BundlesRequest) (*FetchX509BundlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchX509Bundles not implemented")
}
func (UnimplementedSpiffeWorkloadAPIServer) FetchJWTSVID(context.Context, *FetchJWTSVIDRequest) (*FetchJWTSVIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchJWTSVID not implemented")
}
func (UnimplementedSpiffeWorkloadAPIServer) FetchJWTBundles(context.Context, *FetchJWTBundlesRequest) (*FetchJWTBundlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchJWTBundles not implemented")
}
func (UnimplementedSpiffeWorkloadAPIServer) mustEmbedUnimplementedSpiffeWorkloadAPIServer() {}
func (UnimplementedSpiffeWorkloadAPIServer) testEmbeddedByValue()                           {}

// UnsafeSpiffeWorkloadAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpiffeWorkloadAPIServer will
// result in compilation errors.
type UnsafeSpiffeWorkloadAPIServer interface {
	mustEmbedUnimplementedSpiffeWorkloadAPIServer()
}

func RegisterSpiffeWorkloadAPIServer(s grpc.ServiceRegistrar, srv SpiffeWorkloadAPIServer) {
	// If the following call panics, it indicates UnimplementedSpiffeWorkloadAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpiffeWorkloadAPI_ServiceDesc, srv)
}

func _SpiffeWorkloadAPI_FetchX509SVID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchX509SVIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiffeWorkloadAPIServer).FetchX509SVID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpiffeWorkloadAPI_FetchX509SVID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiffeWorkloadAPIServer).FetchX509SVID(ctx, req.(*FetchX509SVIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiffeWorkloadAPI_FetchX509Bundles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchX509BundlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiffeWorkloadAPIServer).FetchX509Bundles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpiffeWorkloadAPI_FetchX509Bundles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiffeWorkloadAPIServer).FetchX509Bundles(ctx, req.(*FetchX509BundlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiffeWorkloadAPI_FetchJWTSVID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchJWTSVIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiffeWorkloadAPIServer).FetchJWTSVID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpiffeWorkloadAPI_FetchJWTSVID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiffeWorkloadAPIServer).FetchJWTSVID(ctx, req.(*FetchJWTSVIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiffeWorkloadAPI_FetchJWTBundles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchJWTBundlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiffeWorkloadAPIServer).FetchJWTBundles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpiffeWorkloadAPI_FetchJWTBundles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiffeWorkloadAPIServer).FetchJWTBundles(ctx, req.(*FetchJWTBundlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpiffeWorkloadAPI_ServiceDesc is the grpc.ServiceDesc for SpiffeWorkloadAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpiffeWorkloadAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.spirl.serverless.alpha.SpiffeWorkloadAPI",
	HandlerType: (*SpiffeWorkloadAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchX509SVID",
			Handler:    _SpiffeWorkloadAPI_FetchX509SVID_Handler,
		},
		{
			MethodName: "FetchX509Bundles",
			Handler:    _SpiffeWorkloadAPI_FetchX509Bundles_Handler,
		},
		{
			MethodName: "FetchJWTSVID",
			Handler:    _SpiffeWorkloadAPI_FetchJWTSVID_Handler,
		},
		{
			MethodName: "FetchJWTBundles",
			Handler:    _SpiffeWorkloadAPI_FetchJWTBundles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
